# Generated by Django 6.0.2 on 2026-02-28 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Celebrities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='И.Ф.О')),
                ('professia', models.CharField(max_length=50, verbose_name='Профессия')),
                ('discription', models.TextField(verbose_name='Биграфия')),
                ('date', models.DateField(verbose_name='Дата публикации')),
            ],
        ),
    ]
