# Generated by Django 6.0.2 on 2026-02-28 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='celebrities',
            old_name='professia',
            new_name='profession',
        ),
    ]
