# Generated by Django 6.0.2 on 2026-03-03 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_professia_celebrities_profession'),
    ]

    operations = [
        migrations.AddField(
            model_name='celebrities',
            name='content',
            field=models.TextField(blank=True, null=True, verbose_name='Контент'),
        ),
    ]
