# Generated by Django 6.0.2 on 2026-03-03 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_celebrities_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='celebrities',
            name='image',
            field=models.ImageField(null=True, upload_to='main'),
        ),
    ]
