# Generated by Django 6.0.2 on 2026-03-06 09:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_trophy_celebrities_trophy'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wife',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wife', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='celebrities',
            name='wife',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.wife'),
        ),
    ]
