# Generated by Django 6.0.2 on 2026-03-09 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_wife_celebrities_wife'),
    ]

    operations = [
        migrations.AlterField(
            model_name='celebrities',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='main'),
        ),
    ]
