# Generated by Django 6.0.2 on 2026-03-09 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_celebrities_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='celebrities',
            name='wife',
        ),
        migrations.DeleteModel(
            name='Wife',
        ),
    ]
